server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos服务端地址
#      discovery:
#        cluster-name: SH # 配置集群名称，也就是机房位置，例如：SH，上海
mybatis:
  type-aliases-package: com.lyq.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.lyq: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS